test_django/accounts/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.views import (
    login, logout, password_reset, password_reset_done, password_reset_confirm,
    password_reset_complete
    )

urlpatterns = [
    url(r'^login/$', login, {'template_name':'accounts/login.html'}, name='login'),
    url(r'^logout/$', logout, {'template_name':'accounts/logout.html'}, name='logout'),
    url(r'^register/$', views.register, name='register'),
    url(r'^profile/$', views.view_profile, name='view_profile'),
    url(r'^profile/(?P<pk>\d+)/$', views.view_profile, name='view_profile_with_pk'),
    url(r'^profile/edit$', views.edit_profile, name='edit_profile'),
    url(r'^change-password/$', views.change_password, name='change_password'),

    url(r'^reset-password/$', password_reset, {'template_name':'accounts/reset_password.html', 'post_reset_redirect':'accounts:password_reset_done', 'email_template_name':'accounts/reset_password_email.html'},  name='reset_password'),

    url(r'^reset-password/done/$', password_reset_done, {'template_name':'accounts/reset_password_done.html'}, name='password_reset_done'),

    url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', password_reset_confirm, {'template_name':'accounts/reset_password_confirm.html', 'post_reset_redirect':'accounts:password_reset_complete'}, name='password_reset_confirm'),

    url(r'^reset-password/complete/$', password_reset_complete, {'template_name':'accounts/reset_password_complete.html'}, name='password_reset_complete')
]

test_django/app_one/urls.py
from django.conf.urls import url, include
from app_one import views

urlpatterns = [
    url(r'^$', views.HomeView.as_view(), name='home'),
    url(r'^connect/(?P<operation>.+)/(?P<pk>\d+)/$', views.change_friends, name='change_friends'),
]

test_django/test_django/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from test_django import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', views.login_redirect, name='login_redirect'),
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('accounts.urls', namespace='accounts')),
    url(r'^app_one/', include('app_one.urls', namespace='app_one')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

test_django/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save

# Create your models here.
class UserProfileManager(models.Manager):

    def get_queryset(self):
        return super(UserProfileManager, self).get_queryset().filter(city='London')

class UserProfile(models.Model):
    user = models.OneToOneField(User)
    description = models.CharField(max_length=100, default='')
    city = models.CharField(max_length=50, default='')
    website = models.URLField(default='')
    phone = models.IntegerField(default=0)
    image = models.ImageField(upload_to='profile_image', blank=True)

    london = UserProfileManager()
    objects = models.Manager()

    def __str__(self):
        return self.user.username

def create_profile(sender, **kwargs):
    if kwargs['created']:
        user_profile = UserProfile.objects.create(user=kwargs['instance'])

post_save.connect(create_profile, sender=User)

test_django/accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

class RegistrationForm(UserCreationForm):
    email = forms.EmailField(required = True)

    class Meta:
        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2',
        )

    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']

        if commit:
            user.save()

        return user

class EditProfileForm(UserChangeForm):

    class Meta:
        model = User
        fields = (
            'email',
            'first_name',
            'last_name',
            'password',
        )

test_django/accounts/views.py
from django.shortcuts import render, redirect
from accounts.forms import RegistrationForm, EditProfileForm
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserChangeForm, PasswordChangeForm
from django.contrib.auth import update_session_auth_hash, authenticate, login
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.core.urlresolvers import reverse
from django.contrib import messages
# Create your views here.


def register(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)

        if form.is_valid():
            form.save()
            username = request.POST.get('username')
            password = request.POST.get('password1')
            user = authenticate(
                request,
                username=username,
                password=password,
            )
            login(request, user)

            return redirect(reverse('app_one:home'))
    else:
        form = RegistrationForm()

    args = {'form':form}
    return render(request, 'accounts/reg_form.html', args)


def view_profile(request, pk=None):
    storage = messages.get_messages(request)
    if pk:
        user = User.objects.get(pk=pk)
    # args = {'user':request.user}
    else:
        user = request.user
    args = {'user':user,'message':storage}
    return render(request, 'accounts/profile.html', args)


def edit_profile(request):
    if request.method == 'POST':
        form = EditProfileForm(request.POST, instance=request.user)

        if form.is_valid():
            form.save()
            return redirect(reverse('accounts:view_profile'))
    else:
        form=EditProfileForm(instance=request.user)
        args = {'form':form}
        return render(request, 'accounts/edit_profile.html', args)


def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(data=request.POST, user=request.user)

        if form.is_valid():
            form.save()
            messages.success(request, 'Your New Password has been saved.')
            update_session_auth_hash(request, user=form.user)
            return redirect(reverse('account:view_profile'))
    else:
        form=PasswordChangeForm(user=request.user)

    args = {'form':form}
    return render(request, 'accounts/change_password.html', args)

test_django/accounts/templates/accounts/change_password.html
{% extends "base.html" %}

{% block head %}
  <title>Accounts | Profile</title>
{% endblock %}

{% block body %}
<div class="container">
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit</button>
  </form>
</div>
{% endblock %}

test_django/accounts/templates/accounts/edit_profile.html
{% extends "base.html" %}

{% block head %}
  <title>Accounts | Profile</title>
{% endblock %}

{% block body %}
<div class="container">
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit</button>
  </form>
</div>
{% endblock %}

test_django/accounts/templates/accounts/login.html
{% extends "base.html" %}

{% block head %}
  <title>Accounts | Login</title>

  {# CSS File #}
  {% load static %}
  <link rel="stylesheet" href="{% static 'accounts/style.css' %}">
{% endblock %}

{% block body %}
<div class="container">
  <h2>Login</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login</button>
  </form>
</div>
{% endblock %}

test_django/accounts/templates/accounts/logout.html
{% extends "base.html" %}

{% block head %}
  <title>Accounts | Login</title>

  {# CSS File #}
  {% load static %}
  <link rel="stylesheet" href="{% static 'accounts/style.css' %}">
{% endblock %}

{% block body %}
<div class="container">
  <h1>Logged Out!</h1>
  <p>You have Logged Out!</p>
</div>
{% endblock %}

test_django/accounts/templates/accounts/profile.html
{% extends "base.html" %}

{% block head %}
  <title>Accounts | Profile</title>
{% endblock %}

{% block body %}
<div class="container">
  <div class="col-xs-12">
    {% if messages %}
      {% for message in messages %}
      <div class="" role='alert'>
        <center>{{ message }}</center>
      </div>
      {% endfor %}
    {% endif %}
  </div>
  <h1>Profile:</h1>
  <p>Username: {{ user }}</p>
  <p>First Name: {{ user.first_name }}</p>
  <p>Last Name: {{ user.last_name }}</p>
  <p>Email: {{ user.email }}</p>
  <p>Description: {{ user.userprofile.description }}</p>
  <p>City: {{ user.userprofile.city }}</p>
  <p>Website: {{ user.userprofile.website }}</p>
  <p>Phone: {{ user.userprofile.phone }}</p>
  {% if user.userprofile.image %}
    <img src="{{ user.userprofile.image.url }}" width="240">
  {% endif %}

</div>
{% endblock %}

test_django/accounts/templates/accounts/reg_form.html
{% extends "base.html" %}

{% block head %}
<title>Accounts | Register</title>
{% endblock %}

{% block body %}
<div class="container">
  <h1>Register</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Register</button>
  </form>
</div>
{% endblock %}

test_django/accounts/templates/accounts/reset_password.html
{% extends "base.html" %}

{% block head %}
  <title>Accounts | Reset Password</title>

  {# CSS File #}
  {% load static %}
  <link rel="stylesheet" href="{% static 'accounts/style.css' %}">
{% endblock %}

{% block body %}
<div class="container">
  <h2>Password Reset</h2>
  <p>
    Forgotten your password? Enter your email address below, and we'll email instructions for setting a new one.
  </p>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Reset My Password</button>
  </form>
</div>
{% endblock %}

test_django/accounts/templates/accounts/reset_password_complete.html
{% extends "base.html" %}

{% block head %}
  <title>Accounts | Reset Password Complete</title>

  {# CSS File #}
  {% load static %}
  <link rel="stylesheet" href="{% static 'accounts/style.css' %}">
{% endblock %}

{% block body %}
<div class="container">
  <h2>Password Reset Complete</h2>
  <p>

  </p>
  <a href="{% url 'accounts:login' %}">Log in</a>
</div>
{% endblock %}

test_django/accounts/templates/accounts/reset_password_confirm.html
{% extends "base.html" %}

{% block head %}
  <title>Accounts | Reset Password</title>

  {# CSS File #}
  {% load static %}
  <link rel="stylesheet" href="{% static 'accounts/style.css' %}">
{% endblock %}

{% block body %}
<div class="container">
  <h2>Enter New Password</h2>
  <p>

  </p>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Reset Password</button>
  </form>
</div>
{% endblock %}

test_django/accounts/templates/accounts/reset_password_done.html
{% extends "base.html" %}

{% block head %}
  <title>Accounts | Reset Password</title>

  {# CSS File #}
  {% load static %}
  <link rel="stylesheet" href="{% static 'accounts/style.css' %}">
{% endblock %}

{% block body %}
<div class="container">
  <h2>Password Reset Sent</h2>
  <p>
    We've emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.

    If you don't receive an email, please make sure you've entered the address you registered with, and check your spam folder.
  </p>
</div>
{% endblock %}

test_django/accounts/templates/accounts/reset_password_email.html
 	{% load i18n %}{% autoescape off %}
 	{% blocktrans %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktrans %}

 	{% trans "Please go to the following page and choose a new password:" %}
 	{% block reset_link %}
 	{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}
 	{% endblock %}
 	{% trans "Your username, in case you've forgotten:" %} {{ user.get_username }}

 	{% trans "Thanks for using our site!" %}

 	{% blocktrans %}The {{ site_name }} team{% endblocktrans %}

 	{% endautoescape %}